---------- In Power BI ----------
Blank query >> Write and execute the query below >> Convert to table >> Open the lists and expend the columns you want
---------------------------------

let
    contacts_v3 = List.RemoveLastN(List.RemoveFirstN(List.Generate( 
                                    () =>  [nextPage = 0, hasMore = null, counter = 0],
                                        each [counter] <> 2,
                                        each [content = Json.Document(Web.Contents("https://api.hubapi.com/crm/v3/objects/contacts?limit=100&archived=false&property=firstname&property=lastname&property=createdate&property=email&propertyMode=value_and_history&after=" & Text.From([nextPage]),[Headers=[#"Content-Type" = "application/json", Authorization="Bearer ***YOUR***BEARER***TOKEN***FROM***HUBSPOT***"]])),
                                              Table = Table.FromRecords(content[results]),
                                                nextPage = Number.FromText(content[paging][next][after]),
                                                hasMore = try content[paging][next][after] otherwise 0,
                                                counter = if [hasMore] = 0 then [counter] + 1
                                                                            else 0
                                                ],
                                        each [Table]                             
                                ),1),1)
in
    contacts_v3
